SELECT * FROM users u WHERE ID=100;
UPDATE users SET FIRST_NAME = 'Kaio' WHERE ID=100;
SELECT * FROM users u WHERE ID=100;
UPDATE users SET FIRST_NAME = 'Kaio' WHERE id BETWEEN 100 AND 150;
SELECT * FROM users u WHERE id BETWEEN 100 AND 150;