SELECT ID, FIRST_NAME FROM users u ORDER BY FIRST_NAME ASC;

SELECT first_name, COUNT(id) AS TOTAL FROM users u GROUP BY first_name  ORDER BY TOTAL DESC;

SELECT U.FIRST_NAME, COUNT(U.ID) AS TOTAL FROM users u JOIN profile p ON P.user_id = U.ID GROUP BY FIRST_NAME ORDER BY TOTAL DESC;